backend:
  name: github
  repo: Enbry/m-and-com

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: articles
    label: Articles
    folder: content/articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - {
        name: image,
        label: Image,
        widget: object,
        fields:
          [
            { name: image, label: Image, widget: image },
            { name: imageAlt, label: Image Description, widget: string },
          ],
      }
  - name: skills
    label: Skills
    description: Skills
    folder: content/skills
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - {
        name: process,
        label: Process,
        required: true,
        widget: list,
        fields:
          [
            { name: text, label: Text, required: true, widget: string }
          ]
      }
      - { name: icon, label: Icone }
  - name: projects
    label: Projects
    description: Projects
    folder: content/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle, required: false }
      - { name: brief, label: Brief, required: false }
      - {
        name: images,
        label: Image,
        widget: list,
        fields:
          [
            { name: image, label: Image, required: true, widget: image }
          ]
      }
      - {
        name: missions,
        label: Missions,
        required: true,
        widget: list,
        fields:
          [
            { name: text, label: Text, required: true, widget: string }
          ]
      }
      - { label: Link, name: siteLink, widget: string }
      - {
        label: Clients,
        name: clients,
        required: false,
        widget: markdown,
      }
      - {
        label: Medias,
        name: medias,
        required: false,
        widget: markdown,
      }
      - {
        label: Liens,
        name: links,
        required: false,
        widget: markdown
      }
